### ISSUE TITLE
Await Error while Installing 

### ISSUE THREAD

**Issue by pranikz** [abdulrahman1s/fem-dl#12]
While installing it shows this error

```
file:///home/pratyushmahapatra/.npm/_npx/97659feec7ea1822/node_modules/fem-dl/src/index.js:32
} = await prompts([{
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by abdulrahman1s** [comment]
Make sure having nodejs v16 or newer on your device.

**Comment by pranikz** [comment]
This is what I am facing

```
⠸ [0%] Downloading 1. Introduction (Intermediate)/1. Introduction.mkv | Size: 0K⠼ [0%] Downloading 1. Introduction (Intermediate)/1. Introduction.mkv | Size: 0KB | Remaining: 1/47node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error: spawn /home/pratyushmahapatra/node_modules/ffmpeg-static/ffmpeg EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /home/pratyushmahapatra/node_modules/ffmpeg-static/ffmpeg',
  path: '/home/pratyushmahapatra/node_modules/ffmpeg-static/ffmpeg',
  spawnargs: [
    '-y',
    '-headers',
    'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36\r\n' +
      'Origin: https://frontendmasters.com\r\n' +
      'Referer: https://frontendmasters.com/\r\n' +
      'Cookie: CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9zdHJlYW0uZnJvbnRlbmRtYXN0ZXJzLmNvbS8yMDIyLzA0LzE0L01vTHJDRXBFdWgvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY4NjAwOTU5OX19fV19; CloudFront-Signature=HY~SaSdWCOOYsrhewA9whgMewww-hjlabSr-G6-ehB25DYnfRsCHJyX2CpRjygL6v7yqcJAqOZ4dsDTfVeJD8RuenCg~pEiJZIUnKO3Ehssw5pPX7miyDpVrs9A8IVomgIj1Ax-H3BBxJ8IIt6OhNrnOED6dG5EXg3uuoAZsn4AnZQn6TMspujoKlasPgpNwSDS3fQp0kHcNCsAgdp7vjLj7eO-flnRTy1qLoXAETD63LAjn2deGKjsW1FB43y68C1NeoYMJYJM13oDgmoo8ZumVJxjx1n~GWLv9~RX8syZ18iyPXCO3Ff~tXyqbnAOF7qsOG~aojhSrRwKONrirZQ__; CloudFront-Key-Pair-Id=APKAJWB4SBTOPQN6G6BQ; fem_auth_mod=69cc6cf0-a7b1-456a-90a6-82856b7e88e7\r\n',
    '-i',
    'https://stream.frontendmasters.com/2022/04/14/MoLrCEpEuh/qQTKitiVAv/index_720_Q8_5mbps.m3u8',
    '-map',
    '0',
    '-c',
    'copy',
    '/home/pratyushmahapatra/Downloads/Intermediate React, v4/1. Introduction (Intermediate)/Introduction.tmp.mkv'
  ]
}

Node.js v19.2.0

```

**Comment by shrosterneduryden** [comment]
I used node 16.15.1 — works no problem.
